### ISSUE TITLE
Draw chart of : Floating point Value

### ISSUE THREAD

**Issue by GauravCreed** [HackPlan/AndroidCharts#23]
Hi @shaishavgandhi05 

is it possible to draw a chart of floating point value as per your library it only support Integer value, if it's possible then how? please guide me.

Thanks. (_)

**Comment by shaishavgandhi05** [comment]
One way would be to round your floats to the nearest Integer, but keep the labels as floats. Alternatively, if you're trying to plot very minute floating point differences (7.4, 7.5, 7.8, 7.9) you could also multiply by 10, plot it, but keep the labels as the original value. Let me know if that works

**Comment by GauravCreed** [comment]
Hi @shaishavgandhi05 

I think this is not a right way to display, because a floating point value multiply by 10 and after round up that value it may causes a large difference of value that is affected on chart.

so that's not work, if u any other solution then please tell me.

thanks.

**Comment by shaishavgandhi05** [comment]
Could you post the same dataset you're referring to?

**Comment by dacer** [comment]
Floating value support added in v1.0.3
